name: CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.7'

      - name: Run tests
        run: |
          cd $GITHUB_WORKSPACE/
          make init checkstyle test
