name: CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.7'

      - name: Run tests
        run: |
          cd $GITHUB_WORKSPACE/
          make init checkstyle test

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Add profile credentials to ~/.aws/credentials
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile self
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile self
          aws configure set aws_session_token $AWS_SESSION_TOKEN --profile self

      - name: Run integration tests
        run: |
          cd $GITHUB_WORKSPACE/
          make init integration_test environment=dev profile=self
